Remove the agent module as it's separate now.
Signed-off-by: Brian J. Murrell <brian.murrell@intel.com>

diff --git a/chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests b/chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
--- a/chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
+++ b/chroma-manager/tests/framework/integration/installation_and_upgrade/run_tests
@@ -53,7 +53,7 @@ if ${UPGRADE_FROM_3:-false}; then
     . ~/auth.sh
     cat <<"EOF"
 ++ curl -s -k 'https://jenkins-pull:********@jenkins-old.lotus.hpdd.lab.intel.com:8080/job/ieel-b3_1/427/api/xml?xpath=*/artifact/fileName&wrapper=foo'
-++ sed -e 's/.*>\([i]\?ee[l]\?-[0-9\.][0-9\.]*.tar.gz\)<.*/\1/'
+++ sed -e 's/.*>\\([i]\\?ee[l]\\?-[0-9\\.][0-9\\.]*.tar.gz\\)<.*/\\1/'
 EOF
     IEEL_FROM_ARCHIVE=$(curl -s -k "https://jenkins-pull:${OLDJENKINS_PULL}@jenkins-old.lotus.hpdd.lab.intel.com:8080/job/$BUILD_JOB/$BUILD_NUM/api/xml?xpath=*/artifact/fileName&wrapper=foo" | sed -e 's/.*>\([i]\?ee[l]\?-[0-9\.][0-9\.]*.tar.gz\)<.*/\1/')
     echo "+ IEEL_FROM_ARCHIVE=$IEEL_FROM_ARCHIVE"
@@ -67,12 +67,15 @@ EOF
 + curl -k -O https://jenkins-pull:********@jenkins-old.lotus.hpdd.lab.intel.com:8080/job/$BUILD_JOB/$BUILD_NUM/artifact/$IEEL_FROM_ARCHIVE
 EOF
         curl -k -O "https://jenkins-pull:${OLDJENKINS_PULL}@jenkins-old.lotus.hpdd.lab.intel.com:8080/job/$BUILD_JOB/$BUILD_NUM/artifact/$IEEL_FROM_ARCHIVE"
-    set -x
+        set -x
     fi
 else
-    # first fetch and install IML 4.0.3
+    # first fetch and install IML 4.0.4
+    # starting with 4.0.5 might leave us with no not have anything to
+    # upgrade which will fail the upgrade test as it expects that there
+    # should always be an upgrade available
     BUILD_JOB=ieel
-    BUILD_NUM=3015
+    BUILD_NUM=3511
     IEEL_FROM_ARCHIVE=$(curl -s -k "http://jenkins.lotus.hpdd.lab.intel.com/job/$BUILD_JOB/$BUILD_NUM/api/xml?xpath=*/artifact/fileName&wrapper=foo" | sed -re 's/.*>(([i]\?ee[l]\?|iml)-[0-9\.][0-9\.]*.tar.gz)<.*/\1/')
     IEEL_FROM_VER="${IEEL_FROM_ARCHIVE#*-}"
     IEEL_FROM_VER="${IEEL_FROM_VER%.tar.gz}"
@@ -323,17 +326,9 @@ rm -f /usr/lib/python\$python_version/site-packages/sitecustomize.py*"
 if ${UPGRADE_FROM_3:-false}; then
     # the manual bits that need to be done for 3.x to 4.x upgrades
     # see https://github.com/intel-hpdd/intel-manager-for-lustre/issues/125
+    # updated per https://github.com/intel-hpdd/Online-Help/pull/54
     pdsh -l root -R ssh -S -w $(spacelist_to_commalist ${STORAGE_APPLIANCES[@]}) "exec 2>&1; set -xe
-    yum -y install epel-release
-    yum -y install pdsh
-    mv /etc/yum.repos.d/Intel-Lustre-Agent.repo{,.iml-3.x}
-
-    # add any repos required by this test run
-    if [ -n \"$STORAGE_SERVER_REPOS\" ]; then
-        for repo in $STORAGE_SERVER_REPOS; do
-            yum-config-manager --add-repo \$repo
-        done
-    fi" | dshbak -c
+    yum -y install pdsh" | dshbak -c
     if [ ${PIPESTATUS[0]} != 0 ]; then
         exit 1
     fi
@@ -343,13 +338,20 @@ if ${UPGRADE_FROM_3:-false}; then
     pdcp -l root -R ssh -w $(spacelist_to_commalist "${STORAGE_APPLIANCES[@]}") /usr/share/chroma-manager/storage_server.repo /etc/yum.repos.d/Intel-Lustre-Agent.repo"
 
     pdsh -l root -R ssh -S -w "$(spacelist_to_commalist "${STORAGE_APPLIANCES[@]}")" "exec 2>&1; set -xe
-    sed -ne '/\[iml-agent\]/,/^$/p' /etc/yum.repos.d/Intel-Lustre-Agent.repo.iml-3.x >> /etc/yum.repos.d/Intel-Lustre-Agent.repo
+    # add any repos required by this test run
+    if [ -n \"$STORAGE_SERVER_REPOS\" ]; then
+        for repo in $STORAGE_SERVER_REPOS; do
+            curl \"\$repo\" >> /etc/yum.repos.d/Intel-Lustre-Agent.repo
+        done
+    fi
+
     # TODO: we really just need to adjust cache timeouts here to account for
     #       our compressed timelines
     yum clean all
-    yum-config-manager --enable iml-agent
 
-    yum -y upgrade chroma-agent\*
+    yum -y upgrade python2-iml-agent\*
+
+    systemctl enable iml-agent.service
 
     systemctl stop zed
     rmmod zfs zcommon znvpair spl
@@ -380,6 +382,17 @@ if ${UPGRADE_FROM_3:-false}; then
     # agent <-> management communications be taking care of this for us?
 
     sleep 60
+else
+    pdsh -l root -R ssh -S -w "$(spacelist_to_commalist "${STORAGE_APPLIANCES[@]}")" "exec 2>&1; set -xe
+    # add any repos required by this test run
+    if [ -n \"$STORAGE_SERVER_REPOS\" ]; then
+        for repo in $STORAGE_SERVER_REPOS; do
+            curl \"\$repo\" >> /etc/yum.repos.d/Intel-Lustre-Agent.repo
+        done
+    fi" | dshbak -c
+    if [ "${PIPESTATUS[0]}" != "0" ]; then
+        exit 1
+    fi
 fi
 
 echo "End upgrade and setup."
